<wsdl:definitions
     name="EbsPaymentsFtpGetAdapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/BlockChainIntegration/CreateEbsPaymentsRippleABCSImpl/EbsPaymentsFtpGetAdapter"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/BlockChainIntegration/CreateEbsPaymentsRippleABCSImpl/EbsPaymentsFtpGetAdapter"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:imp1="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03"
    >
  <plt:partnerLinkType name="GetPaymentsFile_plt" >
    <plt:role name="GetPaymentsFile_role" >
      <plt:portType name="tns:GetPaymentsFile_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03" schemaLocation="../Schemas/SupplierContact.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="GetPaymentsFile_msg">
        <wsdl:part name="body" element="imp1:Document"/>
    </wsdl:message>
    <wsdl:portType name="GetPaymentsFile_ptt">
        <wsdl:operation name="GetPaymentsFile">
            <wsdl:input message="tns:GetPaymentsFile_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
