<wsdl:definitions
     name="InsertXxBlockchainPaymentsDbAdapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BlockChainIntegration/CreateEbsPaymentsRippleABCSImpl/InsertXxBlockchainPaymentsDbAdapter"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BlockChainIntegration/CreateEbsPaymentsRippleABCSImpl/InsertXxBlockchainPaymentsDbAdapter"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertXxBlockchainPaymentsDbAdapter"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="InsertXxBlockchainPaymentsDbAdapter_plt" >
    <plt:role name="InsertXxBlockchainPaymentsDbAdapter_role" >
      <plt:portType name="tns:InsertXxBlockchainPaymentsDbAdapter_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertXxBlockchainPaymentsDbAdapter" schemaLocation="../Schemas/InsertXxBlockchainPaymentsDbAdapter_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="XxBlockchainPaymentsCollection_msg">
        <wsdl:part name="XxBlockchainPaymentsCollection" element="top:XxBlockchainPaymentsCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertXxBlockchainPaymentsDbAdapter_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:XxBlockchainPaymentsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
